version: "2.1"

volumes:
  config:
  media:
  mqtt:

services:
  # https://blakeblackshear.github.io/frigate/installation
  frigate:
    build: frigate
    privileged: true
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128
    ports:
      - "80:5000"
      - "1935:1935" # RTMP feeds
    volumes:
      - config:/config:ro
      - media:/media/frigate
    tmpfs:
      - /tmp/cache
    shm_size: 2048M
    environment:
      FRIGATE_RTSP_PASSWORD: "balena"
      CONFIG_FILE: "/config/frigate.yml"

  module:
    build: module
    privileged: true
    labels:
      - io.balena.features.kernel-modules=1
    restart: no

  # https://hub.docker.com/r/codercom/code-server
  code-server:
    image: codercom/code-server:3.11.1
    command:
      - --port=8080
      - --auth=none
      - --extensions-dir=/config/.vscode
      - --user-data-dir=/config/.vscode
      - /config
    working_dir: /config
    ports:
      - 8080:8080/tcp
    volumes:
      - config:/config
    user: root

  # https://hub.docker.com/_/eclipse-mosquitto
  mqtt:
    image: eclipse-mosquitto:1.6.15
    ports:
      - 1883:1883

  # https://github.com/balenablocks/hostname
  hostname:
    image: balenablocks/hostname
    restart: no
    labels:
      io.balena.features.supervisor-api: 1
    environment:
      SET_HOSTNAME: frigate
