version: "2.1"

services:
  # https://blakeblackshear.github.io/frigate/installation
  frigate:
    build: frigate
    privileged: true
    ports:
      - "80:5000"
      - "1935:1935" # RTMP feeds
    volumes:
      - config:/config:ro
      - media:/media/frigate
    tmpfs:
      - /tmp/cache
    shm_size: 2048M
    environment:
      FRIGATE_RTSP_PASSWORD: "balena"
      CONFIG_FILE: "/config/frigate.yml"
    labels:
      io.balena.features.kernel-modules: 1

  # https://github.com/balenablocks/hostname
  hostname:
    image: balenablocks/hostname@sha256:b923d6ea886ec48125d2c49e431638d2ef6f4adac574b729b4135cfade3ffdce
    restart: no
    labels:
      io.balena.features.supervisor-api: 1
    environment:
      SET_HOSTNAME: frigate

  # https://hub.docker.com/r/mrlt8/wyze-bridge/tags
  wyze-bridge:
    image: mrlt8/wyze-bridge:2.3.10@sha256:3fa3dc73a9e5762e35de5d0dae12949de9759a10ba466a92b208a93233d4cea0
    volumes:
      - tokens:/tokens

volumes:
  config:
  media:
  tokens:
