#FROM ghcr.io/blakeblackshear/frigate:stable-tensorrt-jp5@sha256:22e3d0b486df52c3d669682254c2b1bf4205fa6ad8bd8f8c9f7fe76b1517005d
FROM ghcr.io/blakeblackshear/frigate:stable-tensorrt-jp4

COPY frigate.yml /config/frigate.yml
